name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 当 main 分支有推送时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: List files for debugging
      run: ls -la ./dist

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_SECRET }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force-with-lease "https://${GITHUB_TOKEN}@github.com/premillos/58_panpan.git" main:gh-pages